name: 拉取并同步上游源码

on:
  schedule:
    - cron: '0 3 */3 * *'   # 每三天 UTC 03:00 运行（北京时间11点）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: 获取 cudy.patch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 克隆官方 ImmortalWRT 上游源码到临时目录，更新 upstream 分支（强制覆盖）
        run: |
          git clone -b openwrt-24.10 --single-branch --depth 1 https://github.com/immortalwrt/immortalwrt.git upstream_tmp
          cd upstream_tmp
          rm -rf .git .github .vscode .devcontainer
          git init
          git add .
          git commit -m "同步官方 upstream openwrt-24.10 源码"
          git remote add origin https://ZT229:${{ secrets.GH_PAT }}@github.com/ZT229/immortalwrt.git
          git branch -M upstream
          git push -f origin upstream
          cd

      - name: 克隆我的远程仓库，应用 patch 到 upstream 并推送
        run: |
          git clone https://ZT229:${{ secrets.GH_PAT }}@github.com/ZT229/immortalwrt.git immortalwrt_repo
          cd immortalwrt_repo
          git checkout upstream
          cd
          
          cp cudy.patch immortalwrt_repo

          git apply cudy.patch
          rm -f cudy.patch

          git add .
          git commit -m "在 upstream 分支应用 cudy.patch"
          git push origin upstream

      - name: 合并 upstream 分支到 main 并推送
        run: |
          git pull
          git checkout main
          if ! git merge upstream --allow-unrelated-histories --no-edit; then
            echo "合并冲突，请手动解决"
            exit 1
          fi
          git push origin main 
